# Generated by Django 4.2.29 on 2026-04-04 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuracoes', '0002_fix_usar_layout_leve'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=80, unique=True, verbose_name='Codigo')),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Perfil de acesso',
                'verbose_name_plural': 'Perfis de acesso',
                'ordering': ('nome', 'codigo'),
            },
        ),
        migrations.CreateModel(
            name='PerfilPermissaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Permissao do perfil',
                'verbose_name_plural': 'Permissoes dos perfis',
                'ordering': ('perfil__nome', 'permissao__modulo', 'permissao__recurso', 'permissao__acao'),
            },
        ),
        migrations.CreateModel(
            name='PermissaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=150, unique=True, verbose_name='Codigo')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('modulo', models.CharField(db_index=True, max_length=50, verbose_name='Modulo')),
                ('recurso', models.CharField(db_index=True, max_length=80, verbose_name='Tela/Recurso')),
                ('acao', models.CharField(db_index=True, max_length=80, verbose_name='Acao')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Permissao do sistema',
                'verbose_name_plural': 'Permissoes do sistema',
                'ordering': ('modulo', 'recurso', 'acao', 'codigo'),
            },
        ),
        migrations.CreateModel(
            name='UsuarioPerfilAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios_vinculados', to='configuracoes.perfilacesso', verbose_name='Perfil base')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vinculo_perfil_acesso', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfis de usuarios',
                'ordering': ('usuario__username',),
            },
        ),
        migrations.AddConstraint(
            model_name='permissaosistema',
            constraint=models.UniqueConstraint(fields=('modulo', 'recurso', 'acao'), name='uniq_permissao_sistema_modulo_recurso_acao'),
        ),
        migrations.AddField(
            model_name='perfilpermissaosistema',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_permissao', to='configuracoes.perfilacesso', verbose_name='Perfil'),
        ),
        migrations.AddField(
            model_name='perfilpermissaosistema',
            name='permissao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_perfil', to='configuracoes.permissaosistema', verbose_name='Permissao'),
        ),
        migrations.AddField(
            model_name='perfilacesso',
            name='permissoes',
            field=models.ManyToManyField(blank=True, related_name='perfis', through='configuracoes.PerfilPermissaoSistema', to='configuracoes.permissaosistema', verbose_name='Permissoes'),
        ),
        migrations.AddConstraint(
            model_name='perfilpermissaosistema',
            constraint=models.UniqueConstraint(fields=('perfil', 'permissao'), name='uniq_perfil_permissao_sistema'),
        ),
    ]
