# Generated by Django 4.2.29 on 2026-04-04 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0011_auditoriafinanceiro'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraLancamentoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa'), ('transferencia', 'Transferencia')], max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regras_lancamento', to='financeiro.categoriafinanceira')),
                ('centro_custo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regras_lancamento', to='financeiro.centrocusto')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regras_lancamento_origem', to='financeiro.contafinanceira')),
                ('conta_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regras_lancamento_destino', to='financeiro.contafinanceira')),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regras_lancamento', to='financeiro.pessoafinanceira')),
            ],
            options={
                'verbose_name': 'Regra de lancamento financeiro',
                'verbose_name_plural': 'Regras de lancamento financeiro',
                'ordering': ['descricao', '-atualizado_em', '-pk'],
            },
        ),
    ]
