# Generated by Django 4.2.29 on 2026-05-01 17:45

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


def carregar_tipos_conta_financeira(apps, schema_editor):
    TipoContaFinanceira = apps.get_model('financeiro', 'TipoContaFinanceira')
    ContaFinanceira = apps.get_model('financeiro', 'ContaFinanceira')

    tipos = [
        ('conta_corrente', 'Conta corrente', 10),
        ('conta_poupanca', 'Conta poupanca', 20),
        ('dinheiro_caixa', 'Dinheiro/caixa', 30),
        ('aplicacao_financeira', 'Aplicacao financeira', 40),
        ('integralizacao_capital', 'Integralizacao de capital', 50),
        ('conta_vinculada_indisponivel', 'Conta vinculada/indisponivel', 60),
        ('outros', 'Outros', 70),
    ]

    for codigo, nome, ordem in tipos:
        TipoContaFinanceira.objects.update_or_create(
            codigo=codigo,
            defaults={
                'nome': nome,
                'descricao': '',
                'ativo': True,
                'ordem': ordem,
            },
        )

    tipo_outros = TipoContaFinanceira.objects.get(codigo='outros')
    ContaFinanceira.objects.filter(tipo_conta__isnull=True).update(tipo_conta=tipo_outros)


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0012_regralancamentofinanceiro'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoContaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de conta financeira',
                'verbose_name_plural': 'Tipos de conta financeira',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='lancamentofinanceiro',
            options={'ordering': ['-data_competencia', '-criado_em'], 'verbose_name': 'Lancamento financeiro', 'verbose_name_plural': 'Lancamentos financeiros'},
        ),
        migrations.AddField(
            model_name='contafinanceira',
            name='disponibilidade',
            field=models.CharField(choices=[('disponivel', 'Disponivel'), ('indisponivel', 'Indisponivel/vinculada')], default='disponivel', max_length=20),
        ),
        migrations.AddField(
            model_name='contafinanceira',
            name='mensagem_indisponibilidade',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contafinanceira',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='contafinanceira',
            name='tipo_conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas', to='financeiro.tipocontafinanceira'),
        ),
        migrations.RunPython(carregar_tipos_conta_financeira, reverse_code=migrations.RunPython.noop),
    ]
