# Generated by Django 4.2.29 on 2026-05-01

from django.db import migrations


def renomear_tipo_conta_investimento(apps, schema_editor):
    TipoContaFinanceira = apps.get_model('financeiro', 'TipoContaFinanceira')
    TipoContaFinanceira.objects.filter(codigo='aplicacao_financeira').update(
        nome='Conta investimento'
    )
    TipoContaFinanceira.objects.filter(codigo='integralizacao_capital').update(
        nome='Integralizacao de capital'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0013_tipocontafinanceira_and_more'),
    ]

    operations = [
        migrations.RunPython(renomear_tipo_conta_investimento, reverse_code=migrations.RunPython.noop),
    ]
