# Generated by Django 4.2.29 on 2026-05-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0014_renomeia_tipo_conta_investimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriafinanceira',
            name='controla_recorrencia_competencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pessoafinanceira',
            name='contribuinte_recorrente',
            field=models.BooleanField(default=False),
        ),
    ]
