# Generated by Django 4.2.29 on 2026-05-06 19:36

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0015_categoriafinanceira_controla_recorrencia_competencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlocacaoCompetenciaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_competencia', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(9999)])),
                ('mes_competencia', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('valor_alocado', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes_competencia', to='financeiro.categoriafinanceira')),
                ('lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes_competencia', to='financeiro.lancamentofinanceiro')),
            ],
            options={
                'verbose_name': 'Alocacao de competencia financeira',
                'verbose_name_plural': 'Alocacoes de competencia financeira',
                'ordering': ['ano_competencia', 'mes_competencia', 'pk'],
            },
        ),
    ]
