# Generated by Django 4.2.29 on 2026-05-08 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financeiro', '0016_alocacaocompetenciafinanceira'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColunaPersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('tipo_dado', models.CharField(choices=[('texto_curto', 'Texto curto'), ('texto_longo', 'Texto longo'), ('inteiro', 'Inteiro'), ('decimal', 'Decimal'), ('monetario', 'Monetario'), ('percentual', 'Percentual'), ('data', 'Data'), ('mes_competencia', 'Mes/competencia'), ('booleano', 'Booleano'), ('lista_opcoes', 'Lista de opcoes'), ('formula_controlada', 'Formula controlada')], max_length=30)),
                ('obrigatoria', models.BooleanField(default=False)),
                ('visivel', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('calculada', models.BooleanField(default=False)),
                ('configuracao_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa'), ('arquivada', 'Arquivada')], default='ativa', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coluna personalizada',
                'verbose_name_plural': 'Colunas personalizadas',
                'ordering': ['tabela_id', 'ordem', 'nome', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='LinhaTabelaPersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('arquivada', 'Arquivada')], default='ativa', max_length=20)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linhas_tabelas_personalizadas_atualizadas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linhas_tabelas_personalizadas_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Linha de tabela personalizada',
                'verbose_name_plural': 'Linhas de tabela personalizada',
                'ordering': ['tabela_id', 'ordem', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ValorTabelaPersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_texto', models.TextField(blank=True)),
                ('valor_numero', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('valor_data', models.DateField(blank=True, null=True)),
                ('valor_booleano', models.BooleanField(blank=True, null=True)),
                ('valor_json', models.JSONField(blank=True, null=True)),
                ('valor_calculado', models.JSONField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('coluna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='financeiro.colunapersonalizada')),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='financeiro.linhatabelapersonalizada')),
            ],
            options={
                'verbose_name': 'Valor de tabela personalizada',
                'verbose_name_plural': 'Valores de tabela personalizada',
                'ordering': ['linha_id', 'coluna_id', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='TabelaPersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa'), ('arquivada', 'Arquivada')], default='ativa', max_length=20)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabelas_personalizadas_atualizadas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabelas_personalizadas_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tabela personalizada',
                'verbose_name_plural': 'Tabelas personalizadas',
                'ordering': ['ordem', 'nome', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='linhatabelapersonalizada',
            name='tabela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas', to='financeiro.tabelapersonalizada'),
        ),
        migrations.AddField(
            model_name='colunapersonalizada',
            name='tabela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colunas', to='financeiro.tabelapersonalizada'),
        ),
        migrations.AddConstraint(
            model_name='valortabelapersonalizada',
            constraint=models.UniqueConstraint(fields=('linha', 'coluna'), name='uniq_valor_tabela_personalizada_linha_coluna'),
        ),
    ]
