# Generated by Django 4.2.29 on 2026-05-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0017_colunapersonalizada_linhatabelapersonalizada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valortabelapersonalizada',
            name='valor_numero',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
    ]
