# Generated by Django 4.2.29 on 2026-05-12 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0018_alter_valortabelapersonalizada_valor_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalizadorColunaPersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_totalizador', models.CharField(choices=[('soma', 'Soma'), ('media', 'Media'), ('minimo', 'Minimo'), ('maximo', 'Maximo'), ('contagem', 'Contagem')], max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('coluna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totalizadores', to='financeiro.colunapersonalizada')),
            ],
            options={
                'verbose_name': 'Totalizador de coluna personalizada',
                'verbose_name_plural': 'Totalizadores de colunas personalizadas',
                'ordering': ['coluna_id', 'tipo_totalizador', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='totalizadorcolunapersonalizada',
            constraint=models.UniqueConstraint(fields=('coluna', 'tipo_totalizador'), name='uniq_totalizador_coluna_personalizada_coluna_tipo'),
        ),
    ]
