# Generated by Django 4.2.29 on 2026-05-31 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0019_totalizadorcolunapersonalizada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriafinanceira',
            name='centro_custo_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategorias_padrao', to='financeiro.centrocusto'),
        ),
    ]
