from __future__ import annotations

from django.urls import path
from django.views.generic import RedirectView

from .views import (
    AssinaturaInstitucionalCreateView,
    AssinaturaInstitucionalDeleteView,
    AssinaturaInstitucionalListView,
    AssinaturaInstitucionalUpdateView,
    AuditoriaLancamentoFinanceiroListView,
    CadastroAuxiliarPlanilhaBaseView,
    CategoriaFinanceiraAutocompleteView,
    CategoriaFinanceiraCreateView,
    CategoriaFinanceiraDeleteView,
    CategoriaFinanceiraExportacaoView,
    CategoriaFinanceiraListView,
    CategoriaFinanceiraUpdateView,
    ConfiguracaoInstitucionalCreateView,
    ConfiguracaoInstitucionalDeleteView,
    ConfiguracaoInstitucionalListView,
    ConfiguracaoInstitucionalUpdateView,
    CentroCustoAutocompleteView,
    CentroCustoCreateView,
    CentroCustoDeleteView,
    CentroCustoExportacaoView,
    CentroCustoListView,
    CentroCustoUpdateView,
    ContaFinanceiraAutocompleteView,
    ContaFinanceiraCreateView,
    ContaFinanceiraDeleteView,
    ContaFinanceiraExportacaoView,
    ContaFinanceiraExtratoView,
    ContaFinanceiraListView,
    ContaFinanceiraUpdateView,
    EvolucaoCategoriasFinanceiroView,
    ExtratoFinanceiroView,
    FinanceiroHomeView,
    BalanceteInstitucionalFinanceiroView,
    FrequenciaCompetenciasView,
    LancamentoFinanceiroCreateView,
    LancamentoFinanceiroCloneView,
    LancamentoFinanceiroAcoesLoteView,
    LancamentoFinanceiroDeleteView,
    LancamentoFinanceiroExportacaoView,
    LancamentoFinanceiroGrupoRateioCloneView,
    LancamentoFinanceiroGrupoRateioDeleteView,
    LancamentoFinanceiroGrupoRateioUpdateView,
    LancamentoFinanceiroImportacaoExportacaoView,
    LancamentoFinanceiroImportacaoInconsistenciasView,
    LancamentoFinanceiroImportacaoModeloView,
    LancamentoFinanceiroListView,
    LancamentoFinanceiroReciboLoteView,
    LancamentoFinanceiroReciboEspecialSelecionarFavorecidoView,
    LancamentoFinanceiroReciboEspecialView,
    LancamentoFinanceiroReciboView,
    LancamentoFinanceiroRecibosPorFavorecidoView,
    LancamentoFinanceiroTermoAnualQuitacaoView,
    LancamentoFinanceiroTermosAnuaisQuitacaoPorFavorecidoView,
    LancamentoFinanceiroUpdateView,
    PessoaFinanceiraAutocompleteView,
    PessoaFinanceiraCreateView,
    PessoaFinanceiraDeleteView,
    PessoaFinanceiraExportacaoView,
    PessoaFinanceiraHistoricoView,
    PessoaFinanceiraListView,
    PessoaFinanceiraUltimosLancamentosView,
    PessoaFinanceiraUpdateView,
    PrestacaoContasFinanceiroView,
    ResumoFinanceiroView,
    RegraLancamentoFinanceiroSugestaoView,
    TabelaPersonalizadaColunaCreateView,
    TabelaPersonalizadaColunaListView,
    TabelaPersonalizadaColunaUpdateView,
    TabelaPersonalizadaCreateView,
    TabelaPersonalizadaLinhaCreateView,
    TabelaPersonalizadaLinhaExportXlsxView,
    TabelaPersonalizadaLinhaListView,
    TabelaPersonalizadaLinhaUpdateView,
    TabelaPersonalizadaListView,
    TabelaPersonalizadaUpdateView,
)

app_name = 'financeiro'

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='financeiro:lancamento-list', permanent=False), name='home'),
    path('inicio/', FinanceiroHomeView.as_view(), name='home-secundaria'),
    path('extratos/', ExtratoFinanceiroView.as_view(), name='extrato-list'),
    path('auditoria/lancamentos/', AuditoriaLancamentoFinanceiroListView.as_view(), name='auditoria-lancamento-list'),
    path('prestacao-contas/', PrestacaoContasFinanceiroView.as_view(), name='prestacao-contas'),
    path(
        'balancete-institucional/',
        BalanceteInstitucionalFinanceiroView.as_view(),
        name='balancete-institucional',
    ),
    path('resumo/', ResumoFinanceiroView.as_view(), name='resumo'),
    path('frequencia-competencias/', FrequenciaCompetenciasView.as_view(), name='frequencia-competencias'),
    path('evolucao-categorias/', EvolucaoCategoriasFinanceiroView.as_view(), name='evolucao-categorias'),
    path(
        'controles-internos/tabelas-personalizadas/',
        TabelaPersonalizadaListView.as_view(),
        name='tabela-personalizada-list',
    ),
    path(
        'controles-internos/tabelas-personalizadas/nova/',
        TabelaPersonalizadaCreateView.as_view(),
        name='tabela-personalizada-create',
    ),
    path(
        'controles-internos/tabelas-personalizadas/<int:pk>/editar/',
        TabelaPersonalizadaUpdateView.as_view(),
        name='tabela-personalizada-update',
    ),
    path(
        'controles-internos/tabelas-personalizadas/<int:tabela_id>/colunas/',
        TabelaPersonalizadaColunaListView.as_view(),
        name='tabela-personalizada-coluna-list',
    ),
    path(
        'controles-internos/tabelas-personalizadas/<int:tabela_id>/colunas/nova/',
        TabelaPersonalizadaColunaCreateView.as_view(),
        name='tabela-personalizada-coluna-create',
    ),
    path(
        'controles-internos/tabelas-personalizadas/<int:tabela_id>/colunas/<int:pk>/editar/',
        TabelaPersonalizadaColunaUpdateView.as_view(),
        name='tabela-personalizada-coluna-update',
    ),
    path(
        'controles-internos/tabelas-personalizadas/<int:tabela_id>/linhas/',
        TabelaPersonalizadaLinhaListView.as_view(),
        name='tabela-personalizada-linha-list',
    ),
    path(
        'controles-internos/tabelas-personalizadas/<int:tabela_id>/linhas/nova/',
        TabelaPersonalizadaLinhaCreateView.as_view(),
        name='tabela-personalizada-linha-create',
    ),
    path(
        'controles-internos/tabelas-personalizadas/<int:tabela_id>/linhas/exportar-xlsx/',
        TabelaPersonalizadaLinhaExportXlsxView.as_view(),
        name='tabela-personalizada-linha-export-xlsx',
    ),
    path(
        'controles-internos/tabelas-personalizadas/<int:tabela_id>/linhas/<int:pk>/editar/',
        TabelaPersonalizadaLinhaUpdateView.as_view(),
        name='tabela-personalizada-linha-update',
    ),
    path('autocomplete/pessoas/', PessoaFinanceiraAutocompleteView.as_view(), name='autocomplete-pessoa'),
    path(
        'historico/pessoas/<int:pessoa_id>/ultimos-lancamentos/',
        PessoaFinanceiraUltimosLancamentosView.as_view(),
        name='pessoa-ultimos-lancamentos',
    ),
    path('autocomplete/categorias/', CategoriaFinanceiraAutocompleteView.as_view(), name='autocomplete-categoria'),
    path('autocomplete/contas/', ContaFinanceiraAutocompleteView.as_view(), name='autocomplete-conta'),
    path('autocomplete/centros-custo/', CentroCustoAutocompleteView.as_view(), name='autocomplete-centro-custo'),
    path('contas/', ContaFinanceiraListView.as_view(), name='conta-list'),
    path('contas/nova/', ContaFinanceiraCreateView.as_view(), name='conta-create'),
    path('contas/<int:pk>/extrato/', ContaFinanceiraExtratoView.as_view(), name='conta-extrato'),
    path('contas/<int:pk>/editar/', ContaFinanceiraUpdateView.as_view(), name='conta-update'),
    path('contas/<int:pk>/excluir/', ContaFinanceiraDeleteView.as_view(), name='conta-delete'),
    path('centros-custo/', CentroCustoListView.as_view(), name='centro-custo-list'),
    path('centros-custo/novo/', CentroCustoCreateView.as_view(), name='centro-custo-create'),
    path('centros-custo/<int:pk>/editar/', CentroCustoUpdateView.as_view(), name='centro-custo-update'),
    path('centros-custo/<int:pk>/excluir/', CentroCustoDeleteView.as_view(), name='centro-custo-delete'),
    path('pessoas/', PessoaFinanceiraListView.as_view(), name='pessoa-list'),
    path('pessoas/nova/', PessoaFinanceiraCreateView.as_view(), name='pessoa-create'),
    path('pessoas/<int:pk>/historico/', PessoaFinanceiraHistoricoView.as_view(), name='pessoa-historico'),
    path('pessoas/<int:pk>/editar/', PessoaFinanceiraUpdateView.as_view(), name='pessoa-update'),
    path('pessoas/<int:pk>/excluir/', PessoaFinanceiraDeleteView.as_view(), name='pessoa-delete'),
    path('categorias/', CategoriaFinanceiraListView.as_view(), name='categoria-list'),
    path('categorias/nova/', CategoriaFinanceiraCreateView.as_view(), name='categoria-create'),
    path('categorias/<int:pk>/editar/', CategoriaFinanceiraUpdateView.as_view(), name='categoria-update'),
    path('categorias/<int:pk>/excluir/', CategoriaFinanceiraDeleteView.as_view(), name='categoria-delete'),
    path('assinaturas/', AssinaturaInstitucionalListView.as_view(), name='assinatura-list'),
    path('assinaturas/nova/', AssinaturaInstitucionalCreateView.as_view(), name='assinatura-create'),
    path('assinaturas/<int:pk>/editar/', AssinaturaInstitucionalUpdateView.as_view(), name='assinatura-update'),
    path('assinaturas/<int:pk>/excluir/', AssinaturaInstitucionalDeleteView.as_view(), name='assinatura-delete'),
    path(
        'configuracoes-institucionais/',
        ConfiguracaoInstitucionalListView.as_view(),
        name='configuracao-institucional-list',
    ),
    path(
        'configuracoes-institucionais/nova/',
        ConfiguracaoInstitucionalCreateView.as_view(),
        name='configuracao-institucional-create',
    ),
    path(
        'configuracoes-institucionais/<int:pk>/editar/',
        ConfiguracaoInstitucionalUpdateView.as_view(),
        name='configuracao-institucional-update',
    ),
    path(
        'configuracoes-institucionais/<int:pk>/excluir/',
        ConfiguracaoInstitucionalDeleteView.as_view(),
        name='configuracao-institucional-delete',
    ),
    path('lancamentos/', LancamentoFinanceiroListView.as_view(), name='lancamento-list'),
    path(
        'lancamentos/importacao-exportacao/',
        LancamentoFinanceiroImportacaoExportacaoView.as_view(),
        name='lancamento-importacao-exportacao',
    ),
    path(
        'lancamentos/importacao/modelo/',
        LancamentoFinanceiroImportacaoModeloView.as_view(),
        name='lancamento-importacao-modelo',
    ),
    path(
        'lancamentos/importacao/modelos-cadastros/<slug:slug>/',
        CadastroAuxiliarPlanilhaBaseView.as_view(),
        name='lancamento-importacao-modelo-cadastro-auxiliar',
    ),
    path(
        'lancamentos/importacao/inconsistencias/',
        LancamentoFinanceiroImportacaoInconsistenciasView.as_view(),
        name='lancamento-importacao-inconsistencias',
    ),
    path(
        'lancamentos/exportacao/',
        LancamentoFinanceiroExportacaoView.as_view(),
        name='lancamento-exportacao',
    ),
    path(
        'contas/exportacao/',
        ContaFinanceiraExportacaoView.as_view(),
        name='conta-exportacao',
    ),
    path(
        'pessoas/exportacao/',
        PessoaFinanceiraExportacaoView.as_view(),
        name='pessoa-exportacao',
    ),
    path(
        'centros-custo/exportacao/',
        CentroCustoExportacaoView.as_view(),
        name='centro-custo-exportacao',
    ),
    path(
        'categorias/exportacao/',
        CategoriaFinanceiraExportacaoView.as_view(),
        name='categoria-exportacao',
    ),
    path(
        'lancamentos/acoes-em-lote/',
        LancamentoFinanceiroAcoesLoteView.as_view(),
        name='lancamento-acoes-lote',
    ),
    path('lancamentos/novo/', LancamentoFinanceiroCreateView.as_view(), name='lancamento-create'),
    path(
        'lancamentos/regras/sugestoes/',
        RegraLancamentoFinanceiroSugestaoView.as_view(),
        name='lancamento-regra-sugestoes',
    ),
    path('lancamentos/<int:pk>/clonar/', LancamentoFinanceiroCloneView.as_view(), name='lancamento-clone'),
    path(
        'lancamentos/rateio/<str:grupo_rateio>/editar/',
        LancamentoFinanceiroGrupoRateioUpdateView.as_view(),
        name='lancamento-rateio-update',
    ),
    path(
        'lancamentos/rateio/<str:grupo_rateio>/clonar/',
        LancamentoFinanceiroGrupoRateioCloneView.as_view(),
        name='lancamento-rateio-clone',
    ),
    path(
        'lancamentos/rateio/<str:grupo_rateio>/excluir/',
        LancamentoFinanceiroGrupoRateioDeleteView.as_view(),
        name='lancamento-rateio-delete',
    ),
    path('lancamentos/<int:pk>/editar/', LancamentoFinanceiroUpdateView.as_view(), name='lancamento-update'),
    path('lancamentos/<int:pk>/recibo/', LancamentoFinanceiroReciboView.as_view(), name='lancamento-recibo'),
    path(
        'lancamentos/recibo-especial/selecionar-favorecido/',
        LancamentoFinanceiroReciboEspecialSelecionarFavorecidoView.as_view(),
        name='lancamento-recibo-especial-selecionar-favorecido',
    ),
    path(
        'lancamentos/recibo-especial/',
        LancamentoFinanceiroReciboEspecialView.as_view(),
        name='lancamento-recibo-especial',
    ),
    path('lancamentos/recibo-lote/', LancamentoFinanceiroReciboLoteView.as_view(), name='lancamento-recibo-lote'),
    path('lancamentos/recibos-por-favorecido/', LancamentoFinanceiroRecibosPorFavorecidoView.as_view(), name='lancamento-recibos-por-favorecido'),
    path('lancamentos/termo-anual-quitacao/', LancamentoFinanceiroTermoAnualQuitacaoView.as_view(), name='lancamento-termo-anual-quitacao'),
    path(
        'lancamentos/termos-anuais-quitacao-por-favorecido/',
        LancamentoFinanceiroTermosAnuaisQuitacaoPorFavorecidoView.as_view(),
        name='lancamento-termos-anuais-quitacao-por-favorecido',
    ),
    path('lancamentos/<int:pk>/excluir/', LancamentoFinanceiroDeleteView.as_view(), name='lancamento-delete'),
]
