from __future__ import annotations

from django.urls import path

from .views import (
    AssinaturaInstitucionalCreateView,
    AssinaturaInstitucionalDeleteView,
    AssinaturaInstitucionalListView,
    AssinaturaInstitucionalUpdateView,
    CategoriaFinanceiraAutocompleteView,
    CategoriaFinanceiraCreateView,
    CategoriaFinanceiraDeleteView,
    CategoriaFinanceiraListView,
    CategoriaFinanceiraUpdateView,
    ConfiguracaoInstitucionalCreateView,
    ConfiguracaoInstitucionalDeleteView,
    ConfiguracaoInstitucionalListView,
    ConfiguracaoInstitucionalUpdateView,
    CentroCustoAutocompleteView,
    CentroCustoCreateView,
    CentroCustoDeleteView,
    CentroCustoListView,
    CentroCustoUpdateView,
    ContaFinanceiraAutocompleteView,
    ContaFinanceiraCreateView,
    ContaFinanceiraDeleteView,
    ContaFinanceiraExtratoView,
    ContaFinanceiraListView,
    ContaFinanceiraUpdateView,
    ExtratoFinanceiroView,
    FinanceiroHomeView,
    LancamentoFinanceiroCreateView,
    LancamentoFinanceiroDeleteView,
    LancamentoFinanceiroListView,
    LancamentoFinanceiroReciboView,
    LancamentoFinanceiroUpdateView,
    PessoaFinanceiraAutocompleteView,
    PessoaFinanceiraCreateView,
    PessoaFinanceiraDeleteView,
    PessoaFinanceiraListView,
    PessoaFinanceiraUltimosLancamentosView,
    PessoaFinanceiraUpdateView,
    PrestacaoContasFinanceiroView,
    ResumoFinanceiroView,
)

app_name = 'financeiro'

urlpatterns = [
    path('', FinanceiroHomeView.as_view(), name='home'),
    path('extratos/', ExtratoFinanceiroView.as_view(), name='extrato-list'),
    path('prestacao-contas/', PrestacaoContasFinanceiroView.as_view(), name='prestacao-contas'),
    path('resumo/', ResumoFinanceiroView.as_view(), name='resumo'),
    path('autocomplete/pessoas/', PessoaFinanceiraAutocompleteView.as_view(), name='autocomplete-pessoa'),
    path(
        'historico/pessoas/<int:pessoa_id>/ultimos-lancamentos/',
        PessoaFinanceiraUltimosLancamentosView.as_view(),
        name='pessoa-ultimos-lancamentos',
    ),
    path('autocomplete/categorias/', CategoriaFinanceiraAutocompleteView.as_view(), name='autocomplete-categoria'),
    path('autocomplete/contas/', ContaFinanceiraAutocompleteView.as_view(), name='autocomplete-conta'),
    path('autocomplete/centros-custo/', CentroCustoAutocompleteView.as_view(), name='autocomplete-centro-custo'),
    path('contas/', ContaFinanceiraListView.as_view(), name='conta-list'),
    path('contas/nova/', ContaFinanceiraCreateView.as_view(), name='conta-create'),
    path('contas/<int:pk>/extrato/', ContaFinanceiraExtratoView.as_view(), name='conta-extrato'),
    path('contas/<int:pk>/editar/', ContaFinanceiraUpdateView.as_view(), name='conta-update'),
    path('contas/<int:pk>/excluir/', ContaFinanceiraDeleteView.as_view(), name='conta-delete'),
    path('centros-custo/', CentroCustoListView.as_view(), name='centro-custo-list'),
    path('centros-custo/novo/', CentroCustoCreateView.as_view(), name='centro-custo-create'),
    path('centros-custo/<int:pk>/editar/', CentroCustoUpdateView.as_view(), name='centro-custo-update'),
    path('centros-custo/<int:pk>/excluir/', CentroCustoDeleteView.as_view(), name='centro-custo-delete'),
    path('pessoas/', PessoaFinanceiraListView.as_view(), name='pessoa-list'),
    path('pessoas/nova/', PessoaFinanceiraCreateView.as_view(), name='pessoa-create'),
    path('pessoas/<int:pk>/editar/', PessoaFinanceiraUpdateView.as_view(), name='pessoa-update'),
    path('pessoas/<int:pk>/excluir/', PessoaFinanceiraDeleteView.as_view(), name='pessoa-delete'),
    path('categorias/', CategoriaFinanceiraListView.as_view(), name='categoria-list'),
    path('categorias/nova/', CategoriaFinanceiraCreateView.as_view(), name='categoria-create'),
    path('categorias/<int:pk>/editar/', CategoriaFinanceiraUpdateView.as_view(), name='categoria-update'),
    path('categorias/<int:pk>/excluir/', CategoriaFinanceiraDeleteView.as_view(), name='categoria-delete'),
    path('assinaturas/', AssinaturaInstitucionalListView.as_view(), name='assinatura-list'),
    path('assinaturas/nova/', AssinaturaInstitucionalCreateView.as_view(), name='assinatura-create'),
    path('assinaturas/<int:pk>/editar/', AssinaturaInstitucionalUpdateView.as_view(), name='assinatura-update'),
    path('assinaturas/<int:pk>/excluir/', AssinaturaInstitucionalDeleteView.as_view(), name='assinatura-delete'),
    path(
        'configuracoes-institucionais/',
        ConfiguracaoInstitucionalListView.as_view(),
        name='configuracao-institucional-list',
    ),
    path(
        'configuracoes-institucionais/nova/',
        ConfiguracaoInstitucionalCreateView.as_view(),
        name='configuracao-institucional-create',
    ),
    path(
        'configuracoes-institucionais/<int:pk>/editar/',
        ConfiguracaoInstitucionalUpdateView.as_view(),
        name='configuracao-institucional-update',
    ),
    path(
        'configuracoes-institucionais/<int:pk>/excluir/',
        ConfiguracaoInstitucionalDeleteView.as_view(),
        name='configuracao-institucional-delete',
    ),
    path('lancamentos/', LancamentoFinanceiroListView.as_view(), name='lancamento-list'),
    path('lancamentos/novo/', LancamentoFinanceiroCreateView.as_view(), name='lancamento-create'),
    path('lancamentos/<int:pk>/editar/', LancamentoFinanceiroUpdateView.as_view(), name='lancamento-update'),
    path('lancamentos/<int:pk>/recibo/', LancamentoFinanceiroReciboView.as_view(), name='lancamento-recibo'),
    path('lancamentos/<int:pk>/excluir/', LancamentoFinanceiroDeleteView.as_view(), name='lancamento-delete'),
]
